services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=school'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'