CREATE TABLE ALUNOS (
    ID_ALUNO INT NOT NULL,
    NOME_ALUNO VARCHAR(100) NOT NULL,
    MATRICULA VARCHAR(20),
    DATA_NASCIMENTO DATE
);

CREATE TABLE LIVROS (
    ID_LIVRO INT,
    TITULO VARCHAR(150) NOT NULL,
    AUTOR VARCHAR(100),
    ANO_PUBLICACAO INT,
    QUANTIDADE_ESTOQUE INT DEFAULT 0
);

CREATE TABLE EMPRESTIMOS (
    ID_EMPRESTIMO INT,
    ID_ALUNO INT,
    ID_LIVRO INT,
    DATA_EMPRESTIMO DATE DEFAULT ( CURRENT_DATE ),
    DATA_DEVOLUCAO DATE
);

ALTER TABLE ALUNOS ADD PRIMARY KEY (ID_ALUNO);
ALTER TABLE ALUNOS MODIFY ID_ALUNO INT NOT NULL AUTO_INCREMENT;
ALTER TABLE ALUNOS ADD UNIQUE (MATRICULA);

ALTER TABLE LIVROS ADD PRIMARY KEY (ID_LIVRO);

ALTER TABLE EMPRESTIMOS ADD PRIMARY KEY (ID_EMPRESTIMO);
ALTER TABLE EMPRESTIMOS ADD FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO);
ALTER TABLE EMPRESTIMOS ADD FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(ID_LIVRO);